### ISSUE TITLE
Provide configuration to disable this extension

### ISSUE THREAD

**Issue by parched** [microsoft/vscode-flake8#146] opened 2023-04-19 09:46 UTC
I would like my team to use the Ruff extension for flake8 linting instead of this one.
However, they will have this extension installed for other projects.
Currently, it is a manual step to disable this extension, but it would be much better if there was a setting for it.
Something similar to the formatting provider, perhaps, or just a setting to disable this extension.

**Comment by karthiknadig** [comment] 2023-04-19 17:05
I highly recommend upvoting and leaving a comment on this issue: https://github.com/microsoft/vscode/issues/40239

Thanks for the feature request! We are going to give the community time to provide 👍 upvotes on the opening comment to gauge general interest in this idea. If there's enough upvotes then we will consider this feature request in our future planning. If there's unfortunately not enough upvotes then we will close this issue.

**Comment by karthiknadig** [comment] 2023-04-19 20:51
One thing is if we do it we will need to propagate it to two more extensions at least:
https://github.com/microsoft/vscode-pylint
https://github.com/microsoft/vscode-mypy

This is pycon week so we will discuss this for next iteration, and let you know our decision.

**Comment by luabud** [comment] 2023-04-19 21:15
One way to work around this is to set up a Profile for your team with the Ruff extension, and not the Flake8 one: https://code.visualstudio.com/docs/editor/profiles 

This way even if the Flake8 extension is installed in the default profile, it won't work/activate when working in the new profile.

For example, I have the Flake8 extension installed and enabled in my Default profile:
![image](https://user-images.githubusercontent.com/45497113/233201673-7e07f5db-e4b3-41d2-b166-568d58748c66.png)

Then when I switch to my "Python Scripts" profile, I don't have it installed there: 

![image](https://user-images.githubusercontent.com/45497113/233201526-a2e8b9b5-878f-4cae-b35f-d92f262e4744.png)

**Comment by parched** [comment] 2023-04-19 21:40
@karthiknadig Yes, I was thinking the same with respect to Pylint too as that's an extension some of the developers have installed for other projects.
 
Thanks @luabud I'll have a play with it. I would like developers to just be able to clone the repo and open it VS code and be ready to go.

**Comment by parched** [comment] 2023-04-19 22:02
I tried the profile, but it doesn't look like it'll work, because it turns off all the user's other extensions. E.g, the Vim extension I use is project agnostic.

**Comment by luabud** [comment] 2023-04-24 21:24
@isidorn -- do you have a suggestion for this? We could implement a disable setting for each of our linting extensions, but I'm pretty sure there is a more elegant solution in place already that I'm just missing 🤔

**Comment by isidorn** [comment] 2023-04-25 07:44
The real solution is the one @karthiknadig already linked https://github.com/microsoft/vscode/issues/40239
"Workaround" is to use profiles.
"Another workaround" - @parched create your own extension. The only thing your extension does it disable the extensions you want disabled. Then you add your extension as part of the workspace extension recommendations and you are good.

I do not think a disable setting for each linting extension is the way to go.
This sounds like a VS Code problem. I suggest to close this as a duplicate of some VS Code issue and I think we will tackle this some time in the future.

**Comment by parched** [comment] 2023-04-26 02:15
Interesting, I didn't realise extensions could disable other extensions. I'll raise an issue at ruff to disable this one then.

**Comment by parched** [comment] 2023-04-26 02:34
Based on [this comment](https://github.com/charliermarsh/ruff-vscode/issues/115#issuecomment-1437135548), I've found a suitable workaround until VS Code supports this properly:
```
    "flake8.args": [
        "--select",
        "NONEXISTENTVIOLATION"
    ],
```

**Comment by luabud** [comment] 2023-04-27 00:12
Thank you so much, @isidorn!

Glad you found a workaround, @parched! I'm going to close this issue in favour of https://github.com/microsoft/vscode/issues/40239, as that would be the ideal solution for this anyway.

**Closed by luabud** 2023-04-27 00:12 UTC
Labels: triage-needed
